apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend
  - ./banktransactieservice
  - ./database
  - ./frontend
  - ./grootboekservice
  - ./huishoudboekjeservice
  - ./logservice
  - ./organisatieservice
  - ./unleashservice
  - ./postadressenservice
  - ./alarmenservice
  - ./signalenservice
  - ./authservice
  - ./rapportageservice
  - ./statsdexporter
  - ./prometheus
